# Generated by Django 3.2.6 on 2021-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sku',
            field=models.DecimalField(decimal_places=0, max_digits=999999, null=True),
        ),
    ]
