# Generated by Django 3.2.6 on 2021-08-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileIMG',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
