# Generated by Django 3.2.6 on 2021-08-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='websiteURL',
            field=models.URLField(blank=True),
        ),
    ]
